### Zadanie 1.

Otrzymaliśmy dane w następującej postaci: "{dzień tygodnia};{cztery znaki zawierające wskazanie czujnika}" (zawsze są to 4 znaki!). Napisz skrypt, który wygeneruje raport z konkretnego dnia na prośbę użytkownika:

Poproś o podanie dnia dla którego ma zostać wyliczony raport (wielkość liter nie powinna mieć znaczenia)

Pobierz odpowiednią wartość z danych

Przelicz wskazanie czujnika na temperaturę dzieląc przez wartość z tabeli

Wypisz temperaturę z dokładnością do trzeciego miejsca po przecinku (tak jak na przykładzie) i ze znakiem specjalnym ℃ (\u2103)
    
BONUS. Do punktu 1 dodaj walidację - upewnij się, że użytkownik podał jeden z dni który możemy znaleźć w danych

BONUS. Do punktu 4 dodaj wizualizację temperatury w zakresie 0 do 100 stopni na pasku złożonym z 20 znaków (np. dla 50 stopni, zapełnione jest 10/20 znaków)

Wskazanie czujnika - przelicznik:

Większe niż, lub równe 1400 - 22.5

Pomiędzy 1400, a 1200 - 23.1

Mniejsze niż, lub równe 1200 - 23.5

In [26]:
data = """
monday;1250
tuesday;1405
wednesday;1750
thursday;1100
friday;0800
saturday;1225
sunday;1355
"""

In [27]:
#funkcja zapisująca daty do slownika z podanego zbioru
def data_to_dict(data):

    data_lines = data.strip().split('\n')
    data_dict = {}

    for line in data_lines:
        dat = line.split(';')
        data_dict[dat[0]] = int(dat[1])

    return data_dict

In [28]:
#funkcja pobierajace wartosc dla czytnika
def get_sensor_value(day):
    data_dict = data_to_dict(data)
    
    return data_dict[day]

In [29]:
#funkcja przeliczajaca temperature zgodnie z podanymi danymi
def calculate_temp(value):
    if value >= 1400:
        return value/22.5
    elif 1200 < value < 1400:
        return value/23.1
    else:
        return value/23.5

In [30]:
#funkcja do narysowania temperatury graficznie
def draw_graph(temperature):
    number_of_hash = int(temperature/100 * 20)
    graph = ''
    for index in range(22):
        if index == 0 or index == 21:
            graph += '|'
        elif index <= number_of_hash:
            graph += '#'
        else:
            graph += '-'
    return graph

In [31]:
#generowanie raportu
def generate_raport():
    input_day = input("Proszę o wprowadzenie poprawnego dnia tygodnia: ")
    day_to_check = str(input_day).lower()
    try:
        sensor_value = get_sensor_value(day_to_check)
        temperature_value  = calculate_temp(sensor_value)
        message = f'Dane dla "{day_to_check}"\nWskazanie czujnika: {sensor_value}\nTemperatura: {temperature_value:.03f}\u2103\n0\u2103 '
        message += draw_graph(temperature_value) # wizualizacja grafu - bonus nr 2
        message += ' 100\u2103'
        print (message)
    except:
        print("Proszę o wprowadzenie poprawnego dnia tygodnia: ") # sprawdzenie czy dzień jest poprawny

generate_raport()

Dane dla "monday"
Wskazanie czujnika: 1250
Temperatura: 54.113℃
0℃ |##########----------| 100℃

Przykładowe wyjście

Dane dla "thursday"

Wskazanie czujnika: 1100

Temperatura: 46.809℃

0℃ |#########-----------| 100℃  # BONUS

### Zadanie 2.

Pobierz zbiór danych o zawodnikach NBA: https://www.kaggle.com/justinas/nba-players-data
otwórz go za pomocą Pandas i odpowiedz na pytania:

a) Czy jest jakikolwiek zawodnik spoza USA, który przed NBA uczęszczał do college'u Kentucky?

b) Ile wynosi średni wzrost zawodnika w calach? Czy od pierwszego sezonu w tym zbiorze do teraz powiększył się czy zmniejszył?

c) Kto w badanym okresie rzucił łącznie najwięcej punktów? Czy ta osoba miała też największą średnią punktów na sezon?

d) W której rundzie draftu największy udział procentowy mieli zawodnicy ważący więcej niż 100 kg?

Wstepna analiza:

In [33]:
import pandas as pd

In [34]:
df = pd.read_csv('nba/all_seasons.csv')

In [35]:
df.head()

,Unnamed: 0,player_name,team_abbreviation,age,player_height,player_weight,college,country,draft_year,draft_round,...,pts,reb,ast,net_rating,oreb_pct,dreb_pct,usg_pct,ts_pct,ast_pct,season
0,0,Dennis Rodman,CHI,36.0,198.12,99.790240,Southeastern Oklahoma State,USA,1986,2,...,5.7,16.1,3.1,16.1,0.186,0.323,0.100,0.479,0.113,1996-97
1,1,Dwayne Schintzius,LAC,28.0,215.90,117.933920,Florida,USA,1990,1,...,2.3,1.5,0.3,12.3,0.078,0.151,0.175,0.430,0.048,1996-97
2,2,Earl Cureton,TOR,39.0,205.74,95.254320,Detroit Mercy,USA,1979,3,...,0.8,1.0,0.4,-2.1,0.105,0.102,0.103,0.376,0.148,1996-97
3,3,Ed O'Bannon,DAL,24.0,203.20,100.697424,UCLA,USA,1995,1,...,3.7,2.3,0.6,-8.7,0.060,0.149,0.167,0.399,0.077,1996-97
4,4,Ed Pinckney,MIA,34.0,205.74,108.862080,Villanova,USA,1985,1,...,2.4,2.4,0.2,-11.2,0.109,0.179,0.127,0.611,0.040,1996-97

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12305 entries, 0 to 12304
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         12305 non-null  int64
 1   player_name        12305 non-null  object
 2   team_abbreviation  12305 non-null  object
 3   age                12305 non-null  float64
 4   player_height      12305 non-null  float64
 5   player_weight      12305 non-null  float64
 6   college            10516 non-null  object
 7   country            12305 non-null  object
 8   draft_year         12305 non-null  object
 9   draft_round        12305 non-null  object
 10  draft_number       12305 non-null  object
 11  gp                 12305 non-null  int64
 12  pts                12305 non-null  float64
 13  reb                12305 non-null  float64
 14  ast                12305 non-null  float64
 15  net_rating         12305 non-null  float64
 16  oreb_pct           12305 non-null  float64
 17  dreb_pct           12305 non-null  float64
 18  usg_pct            12305 non-null  float64
 19  ts_pct             12305 non-null  float64
 20  ast_pct            12305 non-null  float64
 21  season             12305 non-null  object
dtypes: float64(12), int64(2), object(8)
memory usage: 2.1+ MB

In [37]:
df.describe()

,Unnamed: 0,age,player_height,player_weight,gp,pts,reb,ast,net_rating,oreb_pct,dreb_pct,usg_pct,ts_pct,ast_pct
count,12305.000000,12305.000000,12305.000000,12305.000000,12305.000000,12305.000000,12305.000000,12305.000000,12305.000000,12305.000000,12305.000000,12305.000000,12305.000000,12305.000000
mean,6152.000000,27.084518,200.611602,100.369926,51.290532,8.172775,3.559155,1.813986,-2.255733,0.054473,0.141014,0.184891,0.511060,0.131358
std,3552.291866,4.335868,9.146321,12.477150,25.095909,5.974957,2.483550,1.794155,12.673254,0.043599,0.062704,0.053390,0.101163,0.094483
min,0.000000,18.000000,160.020000,60.327736,1.000000,0.000000,0.000000,0.000000,-250.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3076.000000,24.000000,193.040000,90.718400,31.000000,3.600000,1.800000,0.600000,-6.400000,0.021000,0.096000,0.149000,0.480000,0.066000
50%,6152.000000,26.000000,200.660000,99.790240,57.000000,6.700000,3.000000,1.200000,-1.300000,0.041000,0.131000,0.181000,0.524000,0.103000
75%,9228.000000,30.000000,208.280000,108.862080,73.000000,11.500000,4.700000,2.400000,3.200000,0.084000,0.180000,0.217000,0.561000,0.178000
max,12304.000000,44.000000,231.140000,163.293120,85.000000,36.100000,16.300000,11.700000,300.000000,1.000000,1.000000,1.000000,1.500000,1.000000

In [38]:
df.columns

Index(['Unnamed: 0', 'player_name', 'team_abbreviation', 'age',
       'player_height', 'player_weight', 'college', 'country', 'draft_year',
       'draft_round', 'draft_number', 'gp', 'pts', 'reb', 'ast', 'net_rating',
       'oreb_pct', 'dreb_pct', 'usg_pct', 'ts_pct', 'ast_pct', 'season'],
      dtype='object')

In [39]:
cols = ['player_name', 'team_abbreviation', 'age',
       'player_height', 'player_weight', 'college', 'country', 'draft_year',
       'draft_round', 'draft_number', 'gp', 'pts', 'reb', 'ast', 'net_rating',
       'oreb_pct', 'dreb_pct', 'usg_pct', 'ts_pct', 'ast_pct', 'season']

In [40]:
for i in cols:
    print(f'Liczba kategorii zmiennej {i}: \n {df[i].value_counts()}')

Liczba kategorii zmiennej player_name:
 player_name
Vince Carter        22
Dirk Nowitzki       21
Kevin Garnett       20
Jamal Crawford      20
Kobe Bryant         20
                    ..
JaJuan Johnson       1
Carldell Johnson     1
Derrick Byars        1
Eric Dawson          1
Micah Potter         1
Name: count, Length: 2463, dtype: int64
Liczba kategorii zmiennej team_abbreviation:
 team_abbreviation
CLE    433
TOR    428
MIA    426
LAC    424
DAL    422
WAS    422
ATL    421
PHI    420
HOU    418
SAS    413
DEN    412
ORL    411
LAL    411
NYK    410
IND    410
MIL    409
GSW    409
POR    407
BOS    407
CHI    406
DET    400
MIN    399
PHX    399
SAC    398
UTA    397
MEM    352
CHA    288
NJN    257
OKC    239
SEA    182
BKN    180
NOP    159
NOH    143
CHH     89
VAN     72
NOK     32
Name: count, dtype: int64
Liczba kategorii zmiennej age:
 age
24.0    1277
23.0    1164
25.0    1141
26.0    1015
27.0     972
28.0     868
29.0     785
22.0     771
30.0     711
31.0     620
32.0     549
21.0     500
33.0     450
34.0     353
20.0     286
35.0     250
36.0     200
37.0     135
38.0      85
19.0      73
39.0      51
40.0      29
41.0       9
42.0       4
18.0       3
43.0       3
44.0       1
Name: count, dtype: int64
Liczba kategorii zmiennej player_height:
 player_height
205.74    1464
208.28    1212
200.66    1204
203.20    1185
198.12    1048
210.82    1022
195.58     953
190.50     841
193.04     730
213.36     713
187.96     543
185.42     499
182.88     281
215.90     200
180.34     115
218.44      89
177.80      60
220.98      46
175.26      26
228.60      17
165.10      13
201.00      13
223.52       8
226.06       7
160.02       5
196.00       5
231.14       3
167.64       1
203.00       1
183.00       1
Name: count, dtype: int64
Liczba kategorii zmiennej player_weight:
 player_weight
99.790240     658
108.862080    611
95.254320     575
97.522280     575
102.058200    553
             ...
138.799152      1
131.995272      1
61.688512       1
154.221280      1
155.582056      1
Name: count, Length: 157, dtype: int64
Liczba kategorii zmiennej college:
 college
Kentucky              420
Duke                  384
North Carolina        344
UCLA                  307
Arizona               279
                     ...
Jacksonville State      1
Alabama A&M             1
Siena                   1
Midwestern State        1
UNC                     1
Name: count, Length: 346, dtype: int64
Liczba kategorii zmiennej country:
 country
USA           10308
Canada          182
France          181
Australia        89
Spain            88
              ...
Sudan (UK)        1
Ghana             1
Denmark           1
Colombia          1
Portugal          1
Name: count, Length: 82, dtype: int64
Liczba kategorii zmiennej draft_year:
 draft_year
Undrafted    2224
1998          454
2003          434
2005          426
2008          410
1996          406
2001          404
2009          384
2004          370
1999          366
2000          365
2011          358
2007          348
1997          345
1995          328
2006          328
2002          325
2012          314
2010          304
2013          297
2014          275
1994          273
2015          248
1992          232
2017          224
2016          222
1993          210
2018          202
2019          172
1990          162
1991          149
1988          127
1989          123
2020          108
1987           90
1985           86
2021           53
1986           52
1984           49
1983           22
1981           16
1982           11
1980            3
1979            3
1963            1
1978            1
1976            1
Name: count, dtype: int64
Liczba kategorii zmiennej draft_round:
 draft_round
1            7071
2            2910
Undrafted    2274
3              20
4              12
0               6
6               5
7               5
8               2
Name: count, dtype: int64
Liczba kategorii zmiennej draft_number:
 draft_number
Undrafted    2277
1             346
5             344
4             334
3             327
             ...
87              1
66              1
82              1
127             1
78              1
Name: count, Length: 76, dtype: int64
Liczba kategorii zmiennej gp:
 gp
82    724
81    414
80    395
79    279
78    270
     ...
25     74
34     67
83     10
85      3
84      1
Name: count, Length: 85, dtype: int64
Liczba kategorii zmiennej pts:
 pts
2.0     169
0.0     156
4.0     147
3.0     141
3.3     130
       ...
30.7      1
26.2      1
32.1      1
31.1      1
30.3      1
Name: count, Length: 314, dtype: int64
Liczba kategorii zmiennej reb:
 reb
2.0     319
1.8     293
1.9     291
2.3     277
1.0     270
       ...
13.9      1
13.4      1
15.4      1
16.3      1
14.7      1
Name: count, Length: 153, dtype: int64
Liczba kategorii zmiennej ast:
 ast
0.3     633
0.4     601
0.5     588
0.6     518
0.8     503
       ...
10.1      2
9.9       2
11.5      1
10.9      1
9.4       1
Name: count, Length: 115, dtype: int64
Liczba kategorii zmiennej net_rating:
 net_rating
-0.3     85
 0.8     84
-1.4     81
-1.9     80
-2.0     79
         ..
-42.8     1
-90.6     1
-44.1     1
 21.5     1
-56.4     1
Name: count, Length: 757, dtype: int64
Liczba kategorii zmiennej oreb_pct:
 oreb_pct
0.000    481
0.017    246
0.015    232
0.023    225
0.021    222
        ...
0.267      1
0.308      1
0.316      1
0.188      1
0.375      1
Name: count, Length: 216, dtype: int64
Liczba kategorii zmiennej dreb_pct:
 dreb_pct
0.000    185
0.100    122
0.111    113
0.098    113
0.099    113
        ...
0.017      1
0.714      1
0.325      1
0.450      1
0.429      1
Name: count, Length: 352, dtype: int64
Liczba kategorii zmiennej usg_pct:
 usg_pct
0.183    120
0.184    115
0.166    112
0.168    111
0.179    111
        ...
0.034      1
0.371      1
0.395      1
0.025      1
0.357      1
Name: count, Length: 345, dtype: int64
Liczba kategorii zmiennej ts_pct:
 ts_pct
0.000    156
0.500    123
0.533    103
0.538    101
0.521    100
        ...
0.737      1
0.145      1
0.248      1
0.369      1
0.280      1
Name: count, Length: 551, dtype: int64
Liczba kategorii zmiennej ast_pct:
 ast_pct
0.000    400
0.063    115
0.068    113
0.077    105
0.074    101
        ...
0.371      1
0.512      1
0.750      1
0.483      1
0.538      1
Name: count, Length: 481, dtype: int64
Liczba kategorii zmiennej season:
 season
2021-22    605
2020-21    540
2017-18    540
2018-19    530
2019-20    529
2014-15    492
2016-17    486
2013-14    482
2011-12    478
2015-16    476
2012-13    469
2004-05    464
2006-07    458
2005-06    458
2010-11    452
2007-08    451
2008-09    445
2009-10    442
2003-04    442
2000-01    441
1996-97    441
2001-02    440
1997-98    439
1998-99    439
1999-00    438
2002-03    428
Name: count, dtype: int64

a) Czy jest jakikolwiek zawodnik spoza USA, który przed NBA uczęszczał do college'u Kentucky?

In [41]:
df[list((df.country != 'USA') & (df.college == 'Kentucky'))]

,Unnamed: 0,player_name,team_abbreviation,age,player_height,player_weight,college,country,draft_year,draft_round,...,pts,reb,ast,net_rating,oreb_pct,dreb_pct,usg_pct,ts_pct,ast_pct,season
1910,1910,Jamaal Magloire,CHH,23.0,208.28,117.933920,Kentucky,Canada,2000,1,...,4.6,4.0,0.4,3.2,0.111,0.195,0.164,0.506,0.042,2000-01
2529,2529,Jamaal Magloire,CHH,24.0,210.82,117.480328,Kentucky,Canada,2000,1,...,8.5,5.6,0.4,3.7,0.116,0.221,0.199,0.623,0.035,2001-02
2799,2799,Jamaal Magloire,NOH,25.0,210.82,117.480328,Kentucky,Canada,2000,1,...,10.3,8.8,1.1,2.4,0.123,0.223,0.174,0.541,0.058,2002-03
3416,3416,Jamaal Magloire,NOH,26.0,210.82,117.480328,Kentucky,Canada,2000,1,...,13.6,10.3,1.0,-1.5,0.108,0.241,0.201,0.551,0.055,2003-04
3803,3803,Jamaal Magloire,NOH,27.0,210.82,117.480328,Kentucky,Canada,2000,1,...,11.7,8.9,1.3,-9.3,0.124,0.229,0.220,0.480,0.076,2004-05
4074,4074,Jamaal Magloire,MIL,28.0,210.82,117.480328,Kentucky,Canada,2000,1,...,9.2,9.5,0.7,-2.4,0.107,0.272,0.175,0.494,0.036,2005-06
4438,4438,Jamaal Magloire,POR,29.0,210.82,120.201880,Kentucky,Canada,2000,1,...,6.5,6.1,0.4,-7.8,0.111,0.257,0.177,0.527,0.030,2006-07
4485,4485,Kelenna Azubuike,GSW,23.0,195.58,99.790240,Kentucky,England,Undrafted,Undrafted,...,7.1,2.3,0.7,-9.9,0.040,0.110,0.187,0.572,0.068,2006-07
4940,4940,Jamaal Magloire,DAL,30.0,210.82,120.201880,Kentucky,Canada,2000,1,...,1.8,2.9,0.2,0.0,0.090,0.269,0.174,0.377,0.043,2007-08
5204,5204,Kelenna Azubuike,GSW,24.0,195.58,99.790240,Kentucky,England,Undrafted,Undrafted,...,8.5,4.0,0.9,0.7,0.063,0.138,0.172,0.534,0.063,2007-08
5366,5366,Jamaal Magloire,MIA,31.0,210.82,120.201880,Kentucky,Canada,2000,1,...,2.9,4.0,0.4,3.3,0.135,0.251,0.129,0.505,0.047,2008-09
5573,5573,Kelenna Azubuike,GSW,25.0,195.58,99.790240,Kentucky,England,Undrafted,Undrafted,...,14.4,5.0,1.6,-1.9,0.050,0.117,0.186,0.562,0.076,2008-09
6087,6087,Kelenna Azubuike,GSW,26.0,195.58,99.790240,Kentucky,England,Undrafted,Undrafted,...,13.9,4.6,1.1,-9.1,0.054,0.141,0.195,0.623,0.070,2009-10
6162,6162,Jamaal Magloire,MIA,32.0,210.82,115.665960,Kentucky,Canada,2000,1,...,2.1,3.4,0.0,-0.6,0.133,0.261,0.131,0.470,0.005,2009-10
6656,6656,Jamaal Magloire,MIA,33.0,210.82,115.665960,Kentucky,Canada,2000,1,...,1.9,3.4,0.2,7.2,0.131,0.352,0.105,0.585,0.031,2010-11
6696,6696,Jamaal Magloire,TOR,34.0,210.82,120.201880,Kentucky,Canada,2000,1,...,1.2,3.3,0.2,6.5,0.087,0.277,0.103,0.360,0.023,2011-12
6826,6826,Enes Kanter,UTA,20.0,210.82,121.109064,Kentucky,Turkey,2011,1,...,4.6,4.2,0.1,-8.2,0.135,0.231,0.169,0.539,0.016,2011-12
7089,7089,Kelenna Azubuike,DAL,28.0,195.58,97.522280,Kentucky,England,Undrafted,Undrafted,...,2.3,0.0,0.0,-22.1,0.000,0.000,0.305,0.438,0.000,2011-12
7398,7398,Enes Kanter,UTA,21.0,210.82,121.109064,Kentucky,Turkey,2011,1,...,7.2,4.3,0.4,3.7,0.147,0.176,0.211,0.588,0.050,2012-13
8023,8023,Enes Kanter,UTA,22.0,210.82,112.037224,Kentucky,Turkey,2011,1,...,12.3,7.5,0.9,-12.8,0.116,0.219,0.232,0.523,0.064,2013-14
8222,8222,Enes Kanter,OKC,23.0,210.82,111.130040,Kentucky,Turkey,2011,1,...,15.5,8.9,0.7,-2.6,0.147,0.210,0.241,0.564,0.044,2014-15
8838,8838,Enes Kanter,OKC,24.0,210.82,111.130040,Kentucky,Turkey,2011,1,...,12.7,8.1,0.4,2.7,0.168,0.256,0.234,0.626,0.032,2015-16
9187,9187,Skal Labissiere,SAC,21.0,210.82,102.058200,Kentucky,Haiti,2016,1,...,8.8,4.9,0.8,-2.9,0.095,0.194,0.212,0.577,0.071,2016-17
9500,9500,Jamal Murray,DEN,20.0,193.04,93.893544,Kentucky,Canada,2016,1,...,9.9,2.6,2.1,1.0,0.026,0.104,0.216,0.518,0.142,2016-17
9516,9516,Enes Kanter,OKC,25.0,210.82,111.130040,Kentucky,Turkey,2011,1,...,14.3,6.7,0.9,-0.1,0.147,0.210,0.275,0.599,0.078,2016-17
9711,9711,Jamal Murray,DEN,21.0,193.04,93.893544,Kentucky,Canada,2016,1,...,16.7,3.7,3.4,3.7,0.033,0.087,0.223,0.576,0.159,2017-18
9939,9939,Skal Labissiere,SAC,22.0,210.82,102.058200,Kentucky,Haiti,2016,1,...,8.7,4.8,1.2,-4.3,0.078,0.157,0.204,0.513,0.088,2017-18
10144,10144,Skal Labissiere,POR,23.0,210.82,106.594120,Kentucky,Haiti,2016,1,...,3.0,2.0,0.5,-8.3,0.051,0.185,0.154,0.593,0.078,2018-19
10150,10150,Shai Gilgeous-Alexander,LAC,20.0,198.12,82.100152,Kentucky,Canada,2018,1,...,10.8,2.8,3.3,-2.0,0.026,0.078,0.182,0.554,0.179,2018-19
10313,10313,Isaac Humphries,ATL,21.0,213.36,117.933920,Kentucky,Australia,Undrafted,Undrafted,...,3.0,2.2,0.0,-17.1,0.055,0.123,0.142,0.357,0.000,2018-19
10570,10570,Jamal Murray,DEN,22.0,193.04,93.893544,Kentucky,Canada,2016,1,...,18.2,4.2,4.8,4.8,0.026,0.101,0.241,0.538,0.220,2018-19
10677,10677,Mychal Mulder,GSW,26.0,190.50,83.460928,Kentucky,Canada,Undrafted,Undrafted,...,11.0,3.3,1.1,6.2,0.016,0.093,0.165,0.533,0.053,2019-20
10767,10767,Trey Lyles,SAS,24.0,205.74,106.140528,Kentucky,Canada,2015,1,...,6.4,5.7,1.1,-2.4,0.056,0.228,0.136,0.557,0.072,2019-20
10813,10813,Wenyen Gabriel,POR,23.0,205.74,92.986360,Kentucky,South Sudan,Undrafted,Undrafted,...,2.1,1.7,0.3,-7.2,0.080,0.148,0.124,0.546,0.046,2019-20
10874,10874,Skal Labissiere,ATL,24.0,208.28,106.594120,Kentucky,Haiti,2016,1,...,5.8,5.1,1.3,1.3,0.105,0.155,0.139,0.588,0.106,2019-20
10879,10879,Shai Gilgeous-Alexander,OKC,21.0,195.58,81.646560,Kentucky,Canada,2018,1,...,19.0,5.9,3.3,3.5,0.020,0.146,0.235,0.568,0.148,2019-20
11043,11043,Jamal Murray,DEN,23.0,193.04,97.522280,Kentucky,Canada,2016,1,...,18.5,4.0,4.8,5.3,0.024,0.101,0.248,0.559,0.228,2019-20
11210,11210,Mychal Mulder,GSW,27.0,190.50,83.460928,Kentucky,Canada,Undrafted,Undrafted,...,5.6,1.0,0.4,2.9,0.010,0.062,0.157,0.613,0.047,2020-21
11353,11353,Wenyen Gabriel,NOP,24.0,205.74,92.986360,Kentucky,South Sudan,Undrafted,Undrafted,...,3.4,2.6,0.5,0.8,0.069,0.135,0.135,0.533,0.063,2020-21
11371,11371,Trey Lyles,SAS,25.0,205.74,106.140528,Kentucky,Canada,2015,1,...,5.0,3.7,0.6,-14.5,0.022,0.213,0.128,0.574,0.060,2020-21
11414,11414,Nick Richards,CHA,23.0,213.36,111.130040,Kentucky,Jamaica,2020,2,...,0.8,0.6,0.1,-10.5,0.056,0.096,0.111,0.542,0.054,2020-21
11443,11443,Shai Gilgeous-Alexander,OKC,22.0,198.12,81.646560,Kentucky,Canada,2018,1,...,23.7,4.7,5.9,-7.7,0.015,0.119,0.283,0.623,0.311,2020-21
11615,11615,Jamal Murray,DEN,24.0,190.50,97.522280,Kentucky,Canada,2016,1,...,21.2,4.0,4.8,8.0,0.023,0.095,0.244,0.592,0.197,2020-21
12033,12033,Shai Gilgeous-Alexander,OKC,23.0,198.12,81.646560,Kentucky,Canada,2018,1,...,24.5,5.0,5.9,-6.4,0.017,0.114,0.298,0.557,0.293,2021-22
12120,12120,Wenyen Gabriel,LAL,25.0,205.74,92.986360,Kentucky,South Sudan,Undrafted,Undrafted,...,5.4,3.7,0.5,6.7,0.105,0.151,0.165,0.549,0.053,2021-22
12133,12133,Trey Lyles,SAC,26.0,205.74,106.140528,Kentucky,Canada,2015,1,...,10.5,5.1,1.2,-7.2,0.056,0.189,0.205,0.588,0.090,2021-22
12153,12153,Olivier Sarr,OKC,23.0,213.36,108.862080,Kentucky,France,Undrafted,Undrafted,...,7.0,4.2,0.9,-2.0,0.078,0.133,0.136,0.672,0.066,2021-22
12231,12231,Mychal Mulder,MIA,28.0,190.50,88.450440,Kentucky,Canada,Undrafted,Undrafted,...,4.1,1.4,0.3,-10.3,0.007,0.089,0.153,0.438,0.031,2021-22
12257,12257,Nick Richards,CHA,24.0,213.36,111.130040,Kentucky,Jamaica,2020,2,...,3.0,1.7,0.3,-13.0,0.086,0.137,0.147,0.689,0.054,2021-22

In [42]:
df[list((df.country != 'USA') & (df.college == 'Kentucky'))].describe()

,Unnamed: 0,age,player_height,player_weight,gp,pts,reb,ast,net_rating,oreb_pct,dreb_pct,usg_pct,ts_pct,ast_pct
count,49.000000,49.000000,49.000000,49.000000,49.000000,49.000000,49.000000,49.000000,49.000000,49.000000,49.000000,49.000000,49.000000,49.000000
mean,8488.775510,24.653061,204.547755,104.585355,50.734694,9.044898,4.416327,1.293878,-2.581633,0.075061,0.169163,0.186571,0.545592,0.080633
std,3098.279242,3.351312,7.983544,12.496782,26.397424,6.145495,2.335536,1.561971,6.972526,0.046314,0.070703,0.050233,0.068550,0.069629
min,1910.000000,20.000000,190.500000,81.646560,3.000000,0.800000,0.000000,0.000000,-22.100000,0.000000,0.000000,0.103000,0.357000,0.000000
25%,6087.000000,23.000000,195.580000,93.893544,26.000000,4.100000,2.900000,0.400000,-7.800000,0.026000,0.114000,0.147000,0.523000,0.043000
50%,9516.000000,24.000000,208.280000,106.140528,56.000000,8.500000,4.000000,0.700000,-1.900000,0.078000,0.155000,0.177000,0.554000,0.060000
75%,11043.000000,26.000000,210.820000,117.480328,75.000000,12.700000,5.100000,1.200000,3.200000,0.111000,0.223000,0.220000,0.588000,0.078000
max,12257.000000,34.000000,213.360000,121.109064,82.000000,24.500000,10.300000,5.900000,8.000000,0.168000,0.352000,0.305000,0.689000,0.311000

Odpowiedz: 49 graczy jest spoza USA i takich co uczęszczli na Uniwersytet Kentucky

b) Ile wynosi średni wzrost zawodnika w calach? Czy od pierwszego sezonu w tym zbiorze do teraz powiększył się czy zmniejszył?

In [43]:
(df['player_height'].mean()) / 2.54

78.9809455857839

Średni wzrost zawodnika w calach wynosi 78.98 "

In [44]:
df.groupby("season")[["player_height"]].mean()

         player_height
season
1996-97     200.994830
1997-98     200.619499
1998-99     200.903007
1999-00     200.920959
2000-01     200.752154
2001-02     201.017909
2002-03     201.520514
2003-04     201.315113
2004-05     201.245733
2005-06     200.920655
2006-07     200.704367
2007-08     200.851486
2008-09     201.196539
2009-10     200.873394
2010-11     201.217832
2011-12     200.832343
2012-13     200.769765
2013-14     200.772946
2014-15     200.838455
2015-16     200.949034
2016-17     200.916790
2017-18     200.457741
2018-19     200.535396
2019-20     198.941059
2020-21     198.914926
2021-22     198.350909

Pierwszy sezon w bazie: 200.995

Ostatni sezon w bazie: 198.350

Sredni wzrost zawodników spadł

c) Kto w badanym okresie rzucił łącznie najwięcej punktów? Czy ta osoba miała też największą średnią punktów na sezon?

In [45]:
df.groupby("player_name")["pts"].sum().sort_values(ascending=False)

player_name
LeBron James        515.1
Kobe Bryant         484.0
Dirk Nowitzki       422.3
Carmelo Anthony     418.3
Kevin Durant        379.4
                    ...
Ibrahim Kutluay       0.0
Guy Rucker            0.0
Greg Whittington      0.0
Gani Lawal            0.0
Jon Teske             0.0
Name: pts, Length: 2463, dtype: float64

LeBron James rzucił najwięcej puntków; 515.1

In [46]:
df.groupby("player_name")["pts"].mean().sort_values(ascending=False)

player_name
LeBron James      27.110526
Kevin Durant      27.100000
Luka Doncic       26.525000
Allen Iverson     26.064286
Trae Young        25.600000
                    ...
William Howard     0.000000
JJ O'Brien         0.000000
Cuonzo Martin      0.000000
Royce White        0.000000
Jon Teske          0.000000
Name: pts, Length: 2463, dtype: float64

Tak - największa śrenia LeBron James 27.11

d) W której rundzie draftu największy udział procentowy mieli zawodnicy ważący więcej niż 100 kg?

In [47]:
df_w = df[df.player_weight > 100]
df_w

,Unnamed: 0,player_name,team_abbreviation,age,player_height,player_weight,college,country,draft_year,draft_round,...,pts,reb,ast,net_rating,oreb_pct,dreb_pct,usg_pct,ts_pct,ast_pct,season
1,1,Dwayne Schintzius,LAC,28.0,215.90,117.933920,Florida,USA,1990,1,...,2.3,1.5,0.3,12.3,0.078,0.151,0.175,0.430,0.048,1996-97
3,3,Ed O'Bannon,DAL,24.0,203.20,100.697424,UCLA,USA,1995,1,...,3.7,2.3,0.6,-8.7,0.060,0.149,0.167,0.399,0.077,1996-97
4,4,Ed Pinckney,MIA,34.0,205.74,108.862080,Villanova,USA,1985,1,...,2.4,2.4,0.2,-11.2,0.109,0.179,0.127,0.611,0.040,1996-97
7,7,Elden Campbell,LAL,28.0,213.36,113.398000,Clemson,USA,1990,1,...,14.9,8.0,1.6,3.3,0.095,0.183,0.222,0.520,0.087,1996-97
11,11,Elmore Spencer,SEA,27.0,213.36,122.469840,Nevada-Las Vegas,USA,1992,1,...,0.0,0.0,0.0,-147.5,0.000,0.000,0.126,0.000,0.000,1996-97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12294,12294,Mason Plumlee,CHA,32.0,210.82,115.212368,Duke,USA,2013,1,...,6.5,7.7,3.1,0.9,0.091,0.205,0.117,0.603,0.165,2021-22
12296,12296,Marvin Bagley III,DET,23.0,210.82,106.594120,Duke,USA,2018,1,...,11.3,7.0,0.8,-5.6,0.084,0.200,0.191,0.551,0.049,2021-22
12297,12297,Marquese Chriss,DAL,24.0,205.74,108.862080,Washington,USA,2016,1,...,4.5,3.0,0.5,-2.1,0.096,0.197,0.205,0.518,0.079,2021-22
12300,12300,Markieff Morris,MIA,32.0,205.74,111.130040,Kansas,USA,2011,1,...,7.6,2.6,1.4,4.5,0.059,0.089,0.197,0.547,0.116,2021-22
12304,12304,Micah Potter,DET,24.0,208.28,112.490816,Wisconsin,USA,Undrafted,Undrafted,...,4.0,3.0,0.0,-56.4,0.095,0.125,0.148,0.505,0.000,2021-22

In [48]:
(df_w["draft_round"].value_counts() / df["draft_round"].value_counts()).sort_values(ascending=False)

draft_round
4            0.750000
1            0.524113
2            0.486942
3            0.400000
6            0.400000
7            0.400000
Undrafted    0.349164
0                 NaN
8                 NaN
Name: count, dtype: float64

Największy udział procentowy mieli zawodnicy ważący więcej niż 100 kg w drafcie nr 4 - 75 %

### Zadanie 3.

Napisz funkcję create_tower, która jako input przyjmuje integera większego od 0
i zwraca listę, która tworzy "piramidę" z tyloma piętrami:
Przykładowe rozwiązanie:
In: create_tower(3)
Out:
[
  '  *  ',
  ' *** ',
  '*****'
]

In [49]:
floors = input("Podaj liczbę całkowitą pięter, większą od 0")

def create_tower(floors):
    try: 
        if int(floors) > 0:
            fl = int(floors)
            for i in range(1, fl + 1):
                print((fl-i)*" "+ i*"*" + (i-1)*"*" + (fl-i)*" ")
                i+=1
        else:
            print("Proszę podać liczbę całkowitą większą od zera") 
    except:
        print("Proszę podać liczbę całkowitą większą od zera")

create_tower(floors)

     *
    ***
   *****
  *******
 *********
***********

### Zadanie 4
. Bonusowe

Napisz gre "kółko i krzyżyk"

Wyświetlaj aktualny stan planszy przy pomocy znaków 'o', 'x', '-' w trzech wierszach Np.:

--x

-x-

oo-

Naprzemiennie pytaj gdzie postawić 'x', a gdzie 'o' przyjmując numer pozycji od 1 do 9 Tzn.:

123

456

789

Zakończ grę gdy jedna ze stron wygra, lub wszystkie miejsca będą zapełnione

Na razie wyświetlaj wszystko po kolei, jedno pod drugim

In [50]:
#nadanie tablicy
def initialize_board():
    return {1: ["-","-","-"],
            2: ["-","-","-"],
            3: ["-","-","-"]}

#funkcja wizualizujaca tablice
def visualize_board(board):
    for pos in board:
        row = ''
        for value in board[pos]:
            row += value
        print(row)
    print("")

#funkcja ktora opisuje pozycje - z pozycji okresla kroty rzad i kolumna w naszej tablicy odpowiada lokalizacji
def get_row_column(position):
    row = (position - 1) // 3 + 1
    if row == 1:
        column = position - row
    elif row == 2:
        column = position - 4
    else: 
        column = position - 7
    return [row, column]

#funkcja ktora nadpisuje nam "-" w naszej tablicy na x i o
def insert_symbol_to_position(board, symbol, position):
    indexes = get_row_column(position)
    symbol_to_update = board[indexes[0]][indexes[1]]
    if symbol_to_update == '-':
        board[indexes[0]][indexes[1]] = symbol
        return True
    return False

#funckja definiująca kolejnosc symboli x i o
def get_symbol(round):
    symbol = ''
    if round % 2 == 0:
        symbol += 'x'
    elif round % 2 != 0:
        symbol += 'o'
    return symbol

#funckja weryfikujaca wygrana
def verify_if_won(position, board):
    indexes = get_row_column(position)
    row = indexes[0]
    column = indexes[1]
    if((board[row][0] == board[row][1]) & (board[row][0] == board[row][2])):
        return True
    if((board[1][column] == board[2][column]) & (board[1][column] == board[3][column])):
        return True
    if board[2][1] == '-':
        return False
    if((board[1][0] == board[2][1]) & (board[1][0] == board[3][2])):
        return True
    if((board[1][2] == board[2][1]) & (board[1][2] == board[3][0])):
        return True

def tic_tac_toe():
    board = initialize_board()

    round = 0
    while round < 9:
        try: 
            symbol = get_symbol(round)

            input_position = int(input(f'Where do you want to put "{symbol}": '))

            if input_position < 1 or input_position > 9:
                print('Wrong position')
                continue

            is_inserted = insert_symbol_to_position(board, symbol, int(input_position))
                
            if is_inserted == False:
                print('This place is already taken, try again')
                continue

            won = verify_if_won(int(input_position),board)
            if won:
                visualize_board(board=board)
                print(f'{symbol} won the round')
                break

            round += 1
        except:
            print("Wrong input")

        visualize_board(board=board)

tic_tac_toe()

--x
---
---

-ox
---
---

-ox
x--
---

oox
x--
---

oox
xx-
---

oox
xxo
---

oox
xxo
x--

x won the round